### ISSUE TITLE
Generate certificate with LetsEncrypt

### ISSUE THREAD

**Issue by IMcPwn** [IMcPwn/browser-backdoor#9]

**Comment by impshum** [comment]
This will be epic.

**Comment by IMcPwn** [comment]
I already have a Bash script that does this, I just haven't added it to the repo yet. I'm considering implementing it directly into bb-server.rb as a command like "gen_cert" or something. Thoughts?

**Comment by IMcPwn** [comment]
@impshum It's all set and included in the latest release: [https://github.com/IMcPwn/browser-backdoor/releases/tag/v1.2](https://github.com/IMcPwn/browser-backdoor/releases/tag/v1.2)
